export const projects = [
  {
    title: 'Modern Website',
    description: "Jag har utvecklat en modern och estetiskt tilltalande webbplats anpassad till dagens digitala trender och krav. Genom att använda de senaste verktygen och teknikerna inom webbutveckling har jag skapat en engagerande och responsiv design som ser bra ut på olika enheter och skärmstorlekar.",
    image: "/images/Web.png",
    tags: ['React', 'Material UI', 'Html', 'Css', 'Javascript', 'React-Hooks'],
    source: "https://github.com/amanuelsen/Modern-website",
    visit: 'https://timely-melba-c5773e.netlify.app/',
    id: 3,
  },
  {
    title: 'Restaurangwebbplats',
    description: "Jag har skapat en restaurangwebbplats med React och JavaScript som levererar en exceptionell matupplevelse. Upptäck lockande menyer, enkel beställning och en visuell fest för smaklökarna.",
    image: "/images/Rest.png",
    tags: ['React', 'Html', 'Css', 'Javascript', 'React-icons'],
    source: "https://github.com/amanuelsen/Restaurant-Websites/tree/master#restaurant-websites",
    visit: "https://senai-web.netlify.app/",
    id: 3,
  },
  {
    title: 'Fullstack Next.js app',
    description: "Jag byggde en Next.js fullstack-app med Google Auth, Tailwind oc javascript. Jag installerade Next.js, skapade användargränssnittet och implementerade Google Authentication med hjälp av Google Authentification API.",
    image: "/images/Pro.png",
    tags: ['React', 'Next.js', 'Tailwind', 'MongoDb', 'Google auth'],
    source: "https://github.com/amanuelsen/Fullstack-next.js",
    visit: "https://nex-js-fullstack-senai-app.vercel.app/",
    id: 3,
  },
  {
    title: 'Klarna-checkout',
    description: "Bygger ett Klarna-inspirerat kassasystem för smidiga online-transaktioner. Användarvänlig gränssnitt, sömlösa betalningar, förbättrad säkerhet och anpassning. Kontinuerlig optimering för en smidig upplevelse.",
    image: "/images/klarna.png",
    tags: ['Javascript', 'Klarna-Api', 'Kassautcheckning', "Css"],
    source: 'https://github.com/amanuelsen/Klarna-checkout',
    id: 3,
  },
  {
    title: 'Spotify-Clone',
    description: "Jag har skapat en Spotify-kopia med Material UI, React Router V6, Spotify-web-api-node och Spotify SDK. Den har ett visuellt tilltalande gränssnitt, sömlös navigation och integration med Spotifys API för dataåtkomst. Användare kan njuta av en engagerande musikuppspelning med spårkontroll. Det var ett spännande projekt som visade på kraften hos dessa tekniker för att återskapa Spotify's essens.",
    image: "/images/spotify.webp",
    tags: ["Material UI",
      "React Router V6",
      "Spotify-web-api-node",
      "Spotify SDK"],
    source: "https://github.com/amanuelsen/spotify-clone",
    visit: "https://64725195ce74732ea03ac530--spotify-clone-senai.netlify.app/",
    id: 3,
  },
  {
    title: 'Youtube Klon',
    description: "Jag har utvecklat en webbplats med hjälp av React, Rest API, Material UI, JavaScript och React Hooks, där användare kan utforska och få information om alla länder. Webbplatsen erbjuder en användarvänlig och interaktiv plattform där man kan söka, filtrera och se detaljerad information om olika länder. Genom att kombinera dessa tekniker har jag skapat en engagerande och funktionell upplevelse för användare att upptäcka och utforska världens länder.",
    image: "/images/YT.webp",
    tags: ['React', 'Material UI', 'Node.js', 'Rapid-Ai', 'REACT-ROUTER-DOM'],
    source: 'https://github.com/amanuelsen/Youtube-clone',
    visit: 'https://brilliant-pasca-6edb68.netlify.app/',
    id: 3,
    },{
    title: 'Flagg-appen',
    description: "Jag har utvecklat en webbplats med hjälp av React, Rest API, Material UI, JavaScript och React Hooks, där användare kan utforska och få information om alla länder. Webbplatsen erbjuder en användarvänlig och interaktiv plattform där man kan söka, filtrera och se detaljerad information om olika länder. Genom att kombinera dessa tekniker har jag skapat en engagerande och funktionell upplevelse för användare att upptäcka och utforska världens länder.",
    image: "/images/länder.jpg",
    tags: ['React', 'Rest-Api', 'Material UI', 'Javascript', 'React-Hooks'],
    source: 'https://github.com/amanuelsen/Land-flag',
    visit: 'https://enchanting-lebkuchen-fef295.netlify.app/',
    id: 3,
    },
    {
    title: 'Inloggnings- och registreringssida',
    description: "Jag har framgångsrikt utvecklat en responsiv inloggningssida som anpassar sig sömlöst till olika skärmstorlekar och säkerställer en optimal användarupplevelse över olika enheter",
    image: "/images/login.png",
    tags: [ 'Html', 'Css', 'Javascript'],
    source: 'https://github.com/amanuelsen/Login-register-page',
    visit: 'https://senai-amn.netlify.app/',
    id: 3,
    },
    {
    title: 'Lösenordsgenerator',
    description: "Jag har byggt en lösenordsgenerator för att generera slumpmässiga lösenord.",
    image: "/images/LS.png",
    tags: ['Html', 'Css', 'Javascript'],
    source: 'https://github.com/amanuelsen/password-gen',
    visit: "https://647354cf6b5fe23d37931db7--serene-crostata-81821e.netlify.app/",
    id: 3,
    },
    ];
    
    export const TimeLineData = [
    { year: 2022, text: 'Började min resa' },
    { year: 2022, text: 'Gick med i   Fullstack TechOver Education' },

    { year: 2022, text: 'Byggde många projekt' },
      { year: 2023, text: 'Intreserad av att hjälpa andra företag ', },
];
